site_name: Climate Tech Handbook
site_url: https://www.climatetechhandbook.com
site_description: Your community source of truth for climate tech solutions.
use_directory_urls: True
theme:
  name: material
  custom_dir: overrides
  palette:
    primary: green
  logo: assets/ct-handbook-logo-cropped.png
  favicon: assets/favicon.ico
  copyright: Copyright 2023 - Differential Design, LLC
  features:
    - navigation.tabs
#   - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - navigation.path
    - navigation.instant
    - search.suggest
  icon:
    repo: fontawesome/brands/git-alt

repo_name: Contribute
repo_url: https://github.com/climate-tech-handbook

extra_css:
  - stylesheets/extra.css

plugins:
# - typeset
#   - tags

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: 🔗
      permalink_title: Link to this section of the page

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


# Additional plugins passed over to `mkdocs.insiders.yml` file

# === NAVIGATION ===

nav:
  - 'Home': index.md
  - 'Solutions':
      - solutions/index.md
      - Electricity:
        - Electricity Sector Overview: sector-electricity.md
      - Food, Agriculture, Land Use:
        - Sector Overview: sector-food-agriculture-and-land-use.md
        - solution-reduced-food-waste.md
      - Transportation:
        - Transportation Sector Overview: sector-transportation.md
        - solutions/public-transit.md
        - solutions/efficient-trucks.md
        - solutions/carpooling.md
        - solutions/electric-cars.md
        - solutions/efficient-ocean-shipping.md
        - solutions/efficient-aviation.md
        - solutions/walkable-cities.md
        - solutions/bicycle-infrastructure.md
        - solutions/telepresence.md
        - solutions/electric-trains.md
        - solutions/hybrid-cars.md
        - solutions/electric-bicycles.md
        - solutions/high-speed-rail.md
      - Buildings:
        - Buildings Sector Overview: sector-buildings.md
        - solutions/refrigerant-management.md
        - solutions/alternative-refrigerants.md
        - solutions/clean-cooking.md
        - solutions/insulation.md
        - solutions/building-automation-systems.md
        - solutions/high-performance-glass.md
        - solutions/smart-thermostats.md
        - solutions/district-heating.md
        - solutions/biogas-for-cooking.md
        - solutions/high-efficiency-heat-pumps.md
        - solutions/solar-hot-water.md
        - solutions/low-flow-fixtures.md
        - solutions/green-and-cool-roofs.md
        - solutions/dynamic-glass.md
        - solutions/building-retrofitting.md
        - solutions/net-zero-buildings.md     
  
  - 'Resources':
      - resources/index.md
      - Career Guide: career-guide.md
      - Technologies: technologies.md
      - Full Glossary: glossary.md

  - 'About':
      - About the Handbook: about/index.md
#     - Frequently Asked Questions: faq.md
      - Contribute: contribute.md