site_name: Climate Tech Handbook
site_url: https://www.climatetechhandbook.com
site_description: Your community source of truth for climate tech solutions.
use_directory_urls: True
theme:
  name: material
  custom_dir: overrides
  palette:
    primary: green
  logo: assets/ct-handbook-logo-cropped.png
  favicon: assets/favicon.ico
  copyright: Copyright 2023 - Differential Design, LLC
  features:
    - navigation.tabs
    #   - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - navigation.path
    - navigation.instant
    - search.suggest
  icon:
    repo: fontawesome/brands/git-alt

repo_name: Contribute
repo_url: https://github.com/climate-tech-handbook/climate-tech-handbook

extra_css:
  - stylesheets/extra.css
  - stylesheets/custom.css

extra_javascript:
  - js/custom.js

## NOTE: plugins need to be passed over to mkdocs.insiders.yml due to paid Insiders version of Material for MKDocs

plugins:
  - tags
  - search
  - include-markdown
  # - social
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: 🔗
      permalink_title: Link to this section of the page

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Additional plugins passed over to `mkdocs.insiders.yml` file

# === NAVIGATION ===

nav:
  - "Home": index.md

  - "Solutions":
      - solutions/index.md
      - Electricity: /solutions/sectors/sector-electricity.md
      - Food, Agriculture, and Land Use: /solutions/sectors/sector-food-agriculture-and-land-use.md
      - Industry: solutions/sectors/sector-industry.md
      - Transportation: solutions/sectors/sector-transportation.md
      - Buildings: solutions/sectors/sector-buildings.md
      - Land Sinks: solutions/sectors/sector-land-sinks.md
      - Coastal and Ocean Sinks: solutions/sectors/sector-coastal-and-ocean-sinks.md
      - Engineered Sinks: solutions/sectors/sector-engineered-sinks.md
      - Health and Education: solutions/sectors/sector-health-and-education.md
      - Climate Adaptation: solutions/sectors/sector-climate-adaptation.md
      - Research and Education: solutions/sectors/sector-research-and-education.md
      - Media and Journalism: solutions/sectors/sector-media-and-journalism.md
      - Advocacy or Policy: solutions/sectors/sector-advocacy-or-policy.md
      - Other: solutions/sectors/sector-other.md

  - "Resources":
      - resources/index.md
      - Career Guide: career-guide.md
      - Technologies: technologies.md
      - Full Glossary: glossary.md

  - "About":
      - About the Handbook: about/index.md
      #     - Frequently Asked Questions: faq.md
      - Contribute: contribute.md

  - "Cheat Sheet":
      - cheatsheet.md
